// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxQrbpgkVPWkou0HiMGGf_cpQ5UK29LQU',
    appId: '1:224740813185:web:7e8779ae1b54a22c2c6080',
    messagingSenderId: '224740813185',
    projectId: 'wp-sayim',
    authDomain: 'wp-sayim.firebaseapp.com',
    storageBucket: 'wp-sayim.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBeFAJPcLyEExlaWKjWooe8w4K_431He8',
    appId: '1:224740813185:android:a9c2d15f08bf60c42c6080',
    messagingSenderId: '224740813185',
    projectId: 'wp-sayim',
    storageBucket: 'wp-sayim.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxwwpDoMO7U2W2pIF_kUITXBb90G4Tzkc',
    appId: '1:224740813185:ios:4ddd81a54a5020352c6080',
    messagingSenderId: '224740813185',
    projectId: 'wp-sayim',
    storageBucket: 'wp-sayim.firebasestorage.app',
    iosBundleId: 'com.example.daytrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxQrbpgkVPWkou0HiMGGf_cpQ5UK29LQU',
    appId: '1:224740813185:web:ce5679768982287a2c6080',
    messagingSenderId: '224740813185',
    projectId: 'wp-sayim',
    authDomain: 'wp-sayim.firebaseapp.com',
    storageBucket: 'wp-sayim.firebasestorage.app',
  );
}
